<?xml version="1.0"?>

<!-- 

	Ant build script for HexEditorDemo.
	This project is under a BSD-style license; see License.txt for details.

	Author:  Robert Futrell
	Version: 0.1
	Date:    16jun2008

-->


<project name="HexEditorDemo" default="make-demo-jar" basedir=".">

	<description>HexEditorDemo build file</description>


	<!-- Set global properties for this build. -->
	<property name="app-name"         value="HexEditorDemo"/>
	<property name="source-dir"       location="src"/>
	<property name="hex-editor-dir"   location="../HexEditor"/>
	<property name="class-dir"        location="ant-classes"/>
	<property name="app-dir"          location="dist"/>
	<property name="debug"            value="true"/>
	<property name="debuglevel"       value="lines,var,source"/>
	<property name="java-level"       value="1.4"/>


	<!-- Compiles all classes. -->
	<target name="compile" description="Compile the source.">
		<!-- Build the HexEditor jar. -->
		<ant antfile="${hex-editor-dir}/build.xml" target="make-jar"
				inheritall="false"/>
		<!-- Build demo-specific classes. -->
		<delete includeEmptyDirs="true" quiet="true" failonerror="false">
			<fileset dir="${class-dir}"/>
		</delete>
		<mkdir dir="${class-dir}"/>
		<javac srcdir="${source-dir}" destdir="${class-dir}"
				classpath="${hex-editor-dir}/dist/HexEditor.jar"
				deprecation="yes"
				debug="${debug}" debuglevel="${debuglevel}"
				source="${java-level}" target="${java-level}">
		</javac>
	</target>


	<!-- Build the executable jar. -->
	<target name="make-demo-jar" depends="compile"
			description="Create the HexEditorDemo jar">
		<delete includeEmptyDirs="true" quiet="true" failonerror="false">
			<fileset dir="${app-dir}"/>
		</delete>
		<mkdir dir="${app-dir}"/>
		<copy todir="${app-dir}">
			<fileset dir="${hex-editor-dir}/dist"/>
		</copy>
		<jar destfile="${app-dir}/${app-name}.jar">
			<fileset dir="${class-dir}"/>
			<fileset dir="i18n"/>
			<fileset dir="icons"/>
			<manifest>
				<attribute name="Main-Class"
					value="org/fife/ui/hex/swing/demo/HexEditorDemoApp"/>
				<attribute name="Class-path"
					value="HexEditor.jar"/>
			</manifest>
		</jar>
	</target>


</project>
